on:
 push:
  branches:
    - master

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Run ARM TTK
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: run ARM TTK
        uses: ./.github/actions
        id: action
      - name: Results
        run: echo "The time was ${{ steps.action.outputs }}"



        