on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run ARM TTK
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: run ARM TTK
        uses: ./
        id: action
      - name: Get the Output
        run: echo "The time was ${{ steps.action.outputs }}"



        